//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBMicro.Data.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankLoanDetail
    {
        public int Id { get; set; }
        public int BankId { get; set; }
        public decimal ROIBelow30Lk { get; set; }
        public decimal ROIAbove30Lk { get; set; }
        public decimal ProcessingFeeBelow30Lk { get; set; }
        public decimal ProcessingFeeAbove30Lk { get; set; }
        public decimal MODCharges { get; set; }
        public decimal DocumentCharges { get; set; }
        public Nullable<decimal> ForeClosureCharges { get; set; }
        public Nullable<decimal> PrePaymentCharges { get; set; }
        public string OffersIfAny { get; set; }
    
        public virtual BankMaster BankMaster { get; set; }
    }
}
